apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-sandbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloud-sandbox
    spec:
      runtimeClassName: gvisor
      containers:
        - name: api
          image: cloud-sandbox:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}

